//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdGateway
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdGateway.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFullname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getFullnameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFirstname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getFirstnameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getLastnameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTelephoneNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTelephoneNoAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMobileNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getMobileNoAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDepartmentByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getDepartmentByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmailByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getEmailByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserALineManager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> isUserALineManagerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserAManagerOfManager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> isUserAManagerOfManagerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLineManagerFullnameByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getLineManagerFullnameByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLineManagerUsernameByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getLineManagerUsernameByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLineManagerToPSSByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getLineManagerToPSSByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.ReturnedMessage> sendmailAsync(string mailFro, string Mailto, string mailbody, string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmailWithAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.ReturnedMessage> sendmailWithAttachmentAsync(string mailFro, string Mailto, string mailbody, string subject, string attachmentpath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getJobLevelByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getJobLevelByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDivisionByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getDivisionByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGroupByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getGroupByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUnitByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getUnitByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBirthDateByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getBirthDateByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBirthDateByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> updateBirthDateByUsernameAsync(string username, string bdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDivisionByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> updateDivisionByUsernameAsync(string username, string division);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateGroupByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> updateGroupByUsernameAsync(string username, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUnitByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> updateUnitByUsernameAsync(string username, string unit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateJobLevelByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> updateJobLevelByUsernameAsync(string username, string level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateLineManagerByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> updateLineManagerByUsernameAsync(string username, string nameOfManager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getResumptionDateByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<System.DateTime> getResumptionDateByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProfessionalQualificationsByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.ProfessionalQualifications[]> getProfessionalQualificationsByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPastEmployersPriorToGTAssurByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.PastEmployers[]> getPastEmployersPriorToGTAssurByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGenderByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getGenderByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkIfUserExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> checkIfUserExistsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDesignationByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getDesignationByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllBirthDaysforToday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.BirthdayCelebrants[]> getAllBirthDaysforTodayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCountOfDirectReports", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<long> getCountOfDirectReportsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllReportsByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string[]> getAllReportsByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserADivisionalDirector", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> isUserADivisionalDirectorAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserAGroupHead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> isUserAGroupHeadAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUserAChiefClientOfficer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<bool> isUserAChiefClientOfficerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastPromotionDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getLastPromotionDateAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreviousPerformancePlacement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<double> getPreviousPerformancePlacementAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStaffIdByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getStaffIdByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getXceedGroupByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> getXceedGroupByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string[]> getAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.ADUser> getUserDataAsync(string username, bool Detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.UpdateUserPictureResponse> UpdateUserPictureAsync(AdGateway.UpdateUserPictureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<AdGateway.Image> GetUserPictureAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPicture2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Threading.Tasks.Task<string> GetUserPicture2Async(string username);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnedMessage
    {
        
        private bool isSuccessfulField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ColorPalette
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Image))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bitmap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bitmap))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Image : MarshalByRefObject
    {
        
        private object tagField;
        
        private ColorPalette paletteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object Tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ColorPalette Palette
        {
            get
            {
                return this.paletteField;
            }
            set
            {
                this.paletteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Bitmap : Image
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ADUser
    {
        
        private string usernameField;
        
        private string fullnameField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string telephoneNoField;
        
        private string mobileNoField;
        
        private string departmentField;
        
        private string emailField;
        
        private bool isLineManagerField;
        
        private bool isManagerOfManagerField;
        
        private int noOfDirectReportField;
        
        private string[] directReportsField;
        
        private string lineManagerFullnameField;
        
        private string lineManagerUsernameField;
        
        private string jobLevelField;
        
        private string divisionField;
        
        private string groupField;
        
        private string unitField;
        
        private string birthDateField;
        
        private string designationField;
        
        private string[] allSubReportsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fullname
        {
            get
            {
                return this.fullnameField;
            }
            set
            {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TelephoneNo
        {
            get
            {
                return this.telephoneNoField;
            }
            set
            {
                this.telephoneNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MobileNo
        {
            get
            {
                return this.mobileNoField;
            }
            set
            {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsLineManager
        {
            get
            {
                return this.isLineManagerField;
            }
            set
            {
                this.isLineManagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsManagerOfManager
        {
            get
            {
                return this.isManagerOfManagerField;
            }
            set
            {
                this.isManagerOfManagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int NoOfDirectReport
        {
            get
            {
                return this.noOfDirectReportField;
            }
            set
            {
                this.noOfDirectReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public string[] DirectReports
        {
            get
            {
                return this.directReportsField;
            }
            set
            {
                this.directReportsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LineManagerFullname
        {
            get
            {
                return this.lineManagerFullnameField;
            }
            set
            {
                this.lineManagerFullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string LineManagerUsername
        {
            get
            {
                return this.lineManagerUsernameField;
            }
            set
            {
                this.lineManagerUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string JobLevel
        {
            get
            {
                return this.jobLevelField;
            }
            set
            {
                this.jobLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Designation
        {
            get
            {
                return this.designationField;
            }
            set
            {
                this.designationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public string[] AllSubReports
        {
            get
            {
                return this.allSubReportsField;
            }
            set
            {
                this.allSubReportsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BirthdayCelebrants
    {
        
        private string celebrantNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CelebrantName
        {
            get
            {
                return this.celebrantNameField;
            }
            set
            {
                this.celebrantNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PastEmployers
    {
        
        private string employerNameField;
        
        private System.DateTime employmentDateField;
        
        private System.DateTime exitDateField;
        
        private string postHeldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmployerName
        {
            get
            {
                return this.employerNameField;
            }
            set
            {
                this.employerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime employmentDate
        {
            get
            {
                return this.employmentDateField;
            }
            set
            {
                this.employmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExitDate
        {
            get
            {
                return this.exitDateField;
            }
            set
            {
                this.exitDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostHeld
        {
            get
            {
                return this.postHeldField;
            }
            set
            {
                this.postHeldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProfessionalQualifications
    {
        
        private string institutionField;
        
        private System.DateTime dateGraduatedField;
        
        private string gradeField;
        
        private string courseNameField;
        
        private string qualificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Institution
        {
            get
            {
                return this.institutionField;
            }
            set
            {
                this.institutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateGraduated
        {
            get
            {
                return this.dateGraduatedField;
            }
            set
            {
                this.dateGraduatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CourseName
        {
            get
            {
                return this.courseNameField;
            }
            set
            {
                this.courseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Qualification
        {
            get
            {
                return this.qualificationField;
            }
            set
            {
                this.qualificationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserPicture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserPictureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        public UpdateUserPictureRequest()
        {
        }
        
        public UpdateUserPictureRequest(string username, byte[] data)
        {
            this.username = username;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserPictureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserPictureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateUserPictureResult;
        
        public UpdateUserPictureResponse()
        {
        }
        
        public UpdateUserPictureResponse(bool UpdateUserPictureResult)
        {
            this.UpdateUserPictureResult = UpdateUserPictureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : AdGateway.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AdGateway.ServiceSoap>, AdGateway.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Threading.Tasks.Task<string> getFullnameAsync(string username)
        {
            return base.Channel.getFullnameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getFirstnameAsync(string username)
        {
            return base.Channel.getFirstnameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getLastnameAsync(string username)
        {
            return base.Channel.getLastnameAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password)
        {
            return base.Channel.AuthenticateUserAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<string> getTelephoneNoAsync(string username)
        {
            return base.Channel.getTelephoneNoAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getMobileNoAsync(string username)
        {
            return base.Channel.getMobileNoAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getDepartmentByUsernameAsync(string username)
        {
            return base.Channel.getDepartmentByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getEmailByUsernameAsync(string username)
        {
            return base.Channel.getEmailByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> isUserALineManagerAsync(string username)
        {
            return base.Channel.isUserALineManagerAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> isUserAManagerOfManagerAsync(string username)
        {
            return base.Channel.isUserAManagerOfManagerAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getLineManagerFullnameByUsernameAsync(string username)
        {
            return base.Channel.getLineManagerFullnameByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getLineManagerUsernameByUsernameAsync(string username)
        {
            return base.Channel.getLineManagerUsernameByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getLineManagerToPSSByUsernameAsync(string username)
        {
            return base.Channel.getLineManagerToPSSByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<AdGateway.ReturnedMessage> sendmailAsync(string mailFro, string Mailto, string mailbody, string subject)
        {
            return base.Channel.sendmailAsync(mailFro, Mailto, mailbody, subject);
        }
        
        public System.Threading.Tasks.Task<AdGateway.ReturnedMessage> sendmailWithAttachmentAsync(string mailFro, string Mailto, string mailbody, string subject, string attachmentpath)
        {
            return base.Channel.sendmailWithAttachmentAsync(mailFro, Mailto, mailbody, subject, attachmentpath);
        }
        
        public System.Threading.Tasks.Task<string> getJobLevelByUsernameAsync(string username)
        {
            return base.Channel.getJobLevelByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getDivisionByUsernameAsync(string username)
        {
            return base.Channel.getDivisionByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getGroupByUsernameAsync(string username)
        {
            return base.Channel.getGroupByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getUnitByUsernameAsync(string username)
        {
            return base.Channel.getUnitByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getBirthDateByUsernameAsync(string username)
        {
            return base.Channel.getBirthDateByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> updateBirthDateByUsernameAsync(string username, string bdate)
        {
            return base.Channel.updateBirthDateByUsernameAsync(username, bdate);
        }
        
        public System.Threading.Tasks.Task<bool> updateDivisionByUsernameAsync(string username, string division)
        {
            return base.Channel.updateDivisionByUsernameAsync(username, division);
        }
        
        public System.Threading.Tasks.Task<bool> updateGroupByUsernameAsync(string username, string group)
        {
            return base.Channel.updateGroupByUsernameAsync(username, group);
        }
        
        public System.Threading.Tasks.Task<bool> updateUnitByUsernameAsync(string username, string unit)
        {
            return base.Channel.updateUnitByUsernameAsync(username, unit);
        }
        
        public System.Threading.Tasks.Task<bool> updateJobLevelByUsernameAsync(string username, string level)
        {
            return base.Channel.updateJobLevelByUsernameAsync(username, level);
        }
        
        public System.Threading.Tasks.Task<bool> updateLineManagerByUsernameAsync(string username, string nameOfManager)
        {
            return base.Channel.updateLineManagerByUsernameAsync(username, nameOfManager);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getResumptionDateByUsernameAsync(string username)
        {
            return base.Channel.getResumptionDateByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<AdGateway.ProfessionalQualifications[]> getProfessionalQualificationsByUsernameAsync(string username)
        {
            return base.Channel.getProfessionalQualificationsByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<AdGateway.PastEmployers[]> getPastEmployersPriorToGTAssurByUsernameAsync(string username)
        {
            return base.Channel.getPastEmployersPriorToGTAssurByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getGenderByUsernameAsync(string username)
        {
            return base.Channel.getGenderByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> checkIfUserExistsAsync(string username)
        {
            return base.Channel.checkIfUserExistsAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getDesignationByUsernameAsync(string username)
        {
            return base.Channel.getDesignationByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<AdGateway.BirthdayCelebrants[]> getAllBirthDaysforTodayAsync()
        {
            return base.Channel.getAllBirthDaysforTodayAsync();
        }
        
        public System.Threading.Tasks.Task<long> getCountOfDirectReportsAsync(string username)
        {
            return base.Channel.getCountOfDirectReportsAsync(username);
        }
        
        public System.Threading.Tasks.Task<string[]> getAllReportsByUsernameAsync(string username)
        {
            return base.Channel.getAllReportsByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> isUserADivisionalDirectorAsync(string username)
        {
            return base.Channel.isUserADivisionalDirectorAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> isUserAGroupHeadAsync(string username)
        {
            return base.Channel.isUserAGroupHeadAsync(username);
        }
        
        public System.Threading.Tasks.Task<bool> isUserAChiefClientOfficerAsync(string username)
        {
            return base.Channel.isUserAChiefClientOfficerAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getLastPromotionDateAsync(string username)
        {
            return base.Channel.getLastPromotionDateAsync(username);
        }
        
        public System.Threading.Tasks.Task<double> getPreviousPerformancePlacementAsync(string username)
        {
            return base.Channel.getPreviousPerformancePlacementAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getStaffIdByUsernameAsync(string username)
        {
            return base.Channel.getStaffIdByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> getXceedGroupByUsernameAsync(string username)
        {
            return base.Channel.getXceedGroupByUsernameAsync(username);
        }
        
        public System.Threading.Tasks.Task<string[]> getAllUsersAsync()
        {
            return base.Channel.getAllUsersAsync();
        }
        
        public System.Threading.Tasks.Task<AdGateway.ADUser> getUserDataAsync(string username, bool Detailed)
        {
            return base.Channel.getUserDataAsync(username, Detailed);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdGateway.UpdateUserPictureResponse> AdGateway.ServiceSoap.UpdateUserPictureAsync(AdGateway.UpdateUserPictureRequest request)
        {
            return base.Channel.UpdateUserPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdGateway.UpdateUserPictureResponse> UpdateUserPictureAsync(string username, byte[] data)
        {
            AdGateway.UpdateUserPictureRequest inValue = new AdGateway.UpdateUserPictureRequest();
            inValue.username = username;
            inValue.data = data;
            return ((AdGateway.ServiceSoap)(this)).UpdateUserPictureAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AdGateway.Image> GetUserPictureAsync(string username)
        {
            return base.Channel.GetUserPictureAsync(username);
        }
        
        public System.Threading.Tasks.Task<string> GetUserPicture2Async(string username)
        {
            return base.Channel.GetUserPicture2Async(username);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://apps.axamansard.com/adgateway/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://apps.axamansard.com/adgateway/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
